Rails 72 fix deprecation warn
Apipie/apipie-rails pull request #948
Opened 2024-12-19 13:33 UTC by Migoo

Fix deprecation method ActiveSupport::Deprecation.warn. Replaced with ActiveSupport::Deprecation.new.warn

2024-12-19 13:53 UTC, ekohl requested changes

2024-12-19 13:53 UTC, ekohl commented on lib/apipie/application.rb
> +      ActiveSupport::Deprecation.new.warn(
Reading https://api.rubyonrails.org/classes/ActiveSupport/Deprecation.html I think you should really set a specific deprecation horizon. So something like:
```suggestion
      ActiveSupport::Deprecation.new('2.0', 'apipie-rails').warn(
```

2025-01-03 08:07 UTC, mathieujobin requested changes
I agree with @ekohl 's comment.

2025-01-06 16:27 UTC, ekohl commented
@Migoo the comment was applicable to to all lines changed and I just didn't want to repeat myself. Could you please apply it everywhere consistently?

2025-01-07 09:01 UTC, Migoo commented
> @Migoo the comment was applicable to to all lines changed and I just didn't want to repeat myself. Could you please apply it everywhere consistently?

My bad ! I just push for all deprecation

2025-01-07 11:28 UTC, ekohl approved these changes
Code looks good to me so I just approved the tests to see if CI agrees.

@mathieujobin do you agree this is now good to go? I also think we should squash the commits on merge.

2025-01-07 11:34 UTC, ekohl commented
Looking at the tests, I see we're not testing on Rails 7.2 so perhaps it should also be added:
https://github.com/Apipie/apipie-rails/blob/62b24b6a2815613f1f9575dc218bdaf425a16988/.github/workflows/build.yml#L11

We can also ignore the Ruby 3.4 failure in this PR, but we should address that as well as change it to Ruby 3.4 final now that's out.

2025-08-19 07:29 UTC, evgeni approved these changes

2025-08-19 07:29 UTC, merged